name: Build Nuitka Binaries

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Nuitka and requirements
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt
      - name: Build with Nuitka
        run: |
          python -m nuitka --onefile main.py
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: main-linux
          path: main.bin

  build-windows:
    runs-on: windows-latest
    env:
      NUITKA_DOWNLOAD_DEPENDENCY_TOOL: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Nuitka and requirements
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt
      - name: Build with Nuitka
        run: |
          python -m nuitka --onefile main.py
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: main-windows
          path: main.exe

